export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const IS_LOADING = 'IS_LOADING';

export const CREATE_NEW_GOAL_SUCCESS = 'CREATE_NEW_GOAL_SUCCESS';
export const GET_GOALS_LIST_SUCCESS = 'GET_GOALS_LIST_SUCCESS';
export const GET_USER_PROGRESS_SUCCESS = 'GET_USER_PROGRESS_SUCCESS';

export const CREATE_NEW_FINANCE_SUCCESS = 'CREATE_NEW_FINANCE_SUCCESS';
export const GET_FINANCES_LIST_SUCCESS = 'GET_FINANCES_LIST_SUCCESS';
