export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CREATE_NEW_GOAL_SUCCESS = 'CREATE_NEW_GOAL_SUCCESS';
export const GET_GOALS_LIST_SUCCESS = 'GET_GOALS_LIST_SUCCESS';
